# Generated by Django 6.0.3 on 2026-03-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('reserved', 'Reserved'), ('available', 'Available'), ('rented', 'Rented')], default='available', max_length=50, null=True),
        ),
    ]
