# Generated by Django 6.0.3 on 2026-03-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_alter_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('available', 'Available'), ('rented', 'Rented'), ('reserved', 'Reserved')], default='available', max_length=50, null=True),
        ),
    ]
