# Generated by Django 5.2.12 on 2026-03-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_app", "0005_alter_book_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="total_rental",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
