# Generated by Django 6.0.3 on 2026-03-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0006_book_total_rental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('available', 'Available'), ('rented', 'Rented'), ('reserved', 'Reserved'), ('sold', 'Sold')], default='available', max_length=50, null=True),
        ),
    ]
